Repository vaticle/typedb-common, pull requests merged in 2019-10, with the labels that each got.

#2 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD
  bin/BUILD
Labels: build, refactor

#4 Change package definitions
  util/Collections.java
  util/Pair.java
  util/Triple.java
Labels: refactor

#5 Use Github credential for release-cleanup
  .circleci/config.yml
Labels: build, refactor

#6 Integrate checking for unused Java dependencies
  .circleci/config.yml
  WORKSPACE
Labels: build, feature
