Repository vaticle/typedb-common, pull requests merged in 2020-12, with the labels that each got.

#63 Integrate dependency-analysis job
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#67 Disable RBE
  .grabl/automation.yml
Labels: priority: blocker, type: build

#68 Fix a the issue where you may get back a null Cancellable from an EventLoop
  concurrent/actor/Actor.java
  concurrent/actor/EventLoop.java
Labels: type: bug

#69 Build Java code to be compatible with older Java
  .bazelrc
Labels: priority: high, type: build

#71 Adapt to new Grabl
  .grabl/automation.yml
Labels: priority: high, type: build, type: refactor

#72 Update bootup scripts
  binary/grakn
  binary/grakn.bat
Labels: type: refactor

#73 Add debug option to grakn runner
  test/server/GraknCoreRunner.java
Labels: type: feature
