Repository vaticle/typedb-common, pull requests merged in 2020-09, with the labels that each got.

#30 Fix Grakn execution script
  binary/grakn
Labels: priority: high, type: bug

#28 Add Objects.className
  BUILD
  util/Objects.java
Labels: priority: low, type: feature

#32 Fix license headers v3
  .bazelrc
  .gitignore
  BUILD
  README.md
  binary/BUILD
  binary/grakn
  binary/grakn-bin.spec
  binary/grakn-docker.sh
  binary/grakn.bat
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  test/server/BUILD
  test/server/rules.bzl
Labels: priority: medium, type: build, x: do not merge

#33 Better license checking
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: build

#34 Delete license from README
  README.md
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: documentation, x: do not merge
