Repository vaticle/typedb-common, pull requests merged in 2020-10, with the labels that each got.

#36 Add debug mode to Grakn executable (shell only)
  .github/CODEOWNERS
  binary/grakn
  binary/grakn.bat
Labels: priority: low, type: feature, x: do not merge

#38 Fix Grakn failing to start in Linux
  binary/grakn
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: bug, x: do not merge

#39 Fix Grakn ignoring all command line arguments
  binary/grakn
Labels: priority: medium, type: bug

#40 Make Grakn use debug logback config in debug mode
  binary/grakn
Labels: priority: medium, type: feature

#41 Add Actor model
  concurrent/actor/Actor.java
  concurrent/actor/ActorPeriodicTask.java
  concurrent/actor/ActorRoot.java
  concurrent/actor/BUILD
  concurrent/actor/eventloop/EventLoop.java
  concurrent/actor/eventloop/EventLoopSingleThreaded.java
  concurrent/actor/eventloop/EventLoopThreadChecker.java
  concurrent/actor/eventloop/GlobalSystem.java
  concurrent/actor/eventloop/LogicalTimerQueue.java
  concurrent/actor/eventloop/Promise.java
  concurrent/actor/test/ActorTest.java
  concurrent/actor/test/BUILD
  concurrent/actor/test/EventLoopTest.java
  concurrent/actor/testkit/BUILD
  concurrent/actor/testkit/TestState.java
Labels: type: feature

#42 Remove eager thread-local execution
  concurrent/actor/eventloop/EventLoopSingleThreaded.java
  concurrent/actor/eventloop/EventLoopThreadChecker.java
  concurrent/actor/eventloop/Promise.java
Labels: type: refactor
