Repository vaticle/typedb-common, pull requests merged in 2020-11, with the labels that each got.

#43 Simplify actor and promise API
  concurrent/actor/Actor.java
  concurrent/actor/eventloop/Promise.java
Labels: type: refactor

#44 Extend NamedThreadFactory with arbitrary prefix
  concurrent/NamedThreadFactory.java
Labels: type: feature

#45 Add event loop group to support multithreading event loops
  concurrent/actor/Actor.java
  concurrent/actor/ActorPeriodicTask.java
  concurrent/actor/eventloop/EventLoop.java
  concurrent/actor/eventloop/EventLoopGroup.java
  concurrent/actor/eventloop/EventLoopSingleThreaded.java
Labels: type: feature

#46 Remove actor periodic task from common
  concurrent/actor/ActorPeriodicTask.java
Labels: type: refactor

#47 Remove Promise from //concurrent/actor
  concurrent/actor/Actor.java
  concurrent/actor/eventloop/EventLoop.java
  concurrent/actor/eventloop/EventLoopGroup.java
  concurrent/actor/eventloop/Promise.java
Labels: type: refactor

#51 Fix console argument off by one bug
  binary/grakn
Labels: type: bug

#52 Allow grakn_java_test to choose a platform-native Grakn artifact
  test/server/GraknCoreRunner.java
  test/server/rules.bzl
Labels: priority: medium, type: build

#48 Adds the functionality to notify Actors of unhandled exceptions
  concurrent/actor/Actor.java
  concurrent/actor/eventloop/EventLoop.java
Labels: type: feature

#54 Wait a bit longer for Grakn to start when testing
  test/server/GraknCoreRunner.java
Labels: priority: medium, type: bug

#56 Add config:version-candidate to automation.yml
  .grabl/automation.yml
Labels: priority: low, type: build

#57 Update collections utils to avoid clashing parameters
  collection/Bytes.java
  collection/Collections.java
Labels: type: refactor

#58 Map Actor library's package structure to the conceptual model
  concurrent/actor/Actor.java
  concurrent/actor/EventLoop.java
  concurrent/actor/EventLoopGroup.java
  concurrent/actor/eventloop/EventLoop.java
  concurrent/actor/eventloop/GlobalSystem.java
  concurrent/actor/eventloop/LogicalTimerQueue.java
Labels: type: refactor

#59 //binary:assemble-linux-apt: adjust path to log dir for Grakn 2.0
  binary/BUILD
Labels: priority: high, type: build, type: refactor

#60 Fix Grakn artifact getting fetched many times when building client
  test/server/rules.bzl
Labels: priority: high, type: build

#61 Support native_grakn_artifact for Windows
  test/server/rules.bzl
Labels: priority: high, type: build, type: refactor
