Repository vaticle/typedb-common, pull requests merged in 2021-06, with the labels that each got.

#109 Improve TypeDBRunner logs and assertions
  test/server/TypeDBClusterRunner.java
  test/server/TypeDBCoreRunner.java
  test/server/TypeDBRunner.java
Labels: type: bug, type: feature

#110 Supports running TypeDB Cluster
  binary/typedb
Labels: type: refactor

#112 'typedb.bat' for TypeDB Cluster
  binary/typedb.bat
Labels: priority: high, type: build, type: feature
