Repository vaticle/typedb-common, pull requests merged in 2021-02, with the labels that each got.

#79 Add a new GraknRunner implementation for Grakn Cluster
  test/server/BUILD
  test/server/GraknClusterRunner.java
  test/server/GraknCoreRunner.java
  test/server/GraknRunner.java
  test/server/GraknRunnerBase.java
  test/server/rules.bzl
Labels: type: feature

#81 Fix testing rules and runner to work under Windows
  binary/grakn
  binary/grakn.bat
  test/server/GraknCoreRunner.java
  test/server/rules.bzl
Labels: priority: high, type: bug, type: build

#82 Resolve data directory in GraknRunnerBase after distribution has been unpacked
  test/server/GraknRunnerBase.java
Labels: priority: high, type: bug

#83 Fix binary script
  binary/grakn
Labels: priority: blocker, type: bug

#84 Fix debug mode in grakn start up script
  binary/grakn
Labels: type: bug

#85 Fix grakn debug mode in linux
  binary/grakn
Labels: type: bug

#86 Remove RPM targets
  .grabl/automation.yml
  binary/BUILD
  binary/grakn-bin.spec
Labels: priority: high, type: build, type: refactor

#88 When running tests, poll used ports to identify when Grakn starts
  test/server/GraknRunnerBase.java
Labels: priority: high, type: bug

#89 Refactor code to work with latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#91 Allow cluster in distribution to run with peer addresses
  test/BUILD
  test/Runner.java
  test/console/ConsoleRunner.java
  test/rules.bzl
  test/server/GraknClusterRunner.java
  test/server/GraknCoreRunner.java
  test/server/GraknRunner.java
Labels: type: feature

#92 Fix bug in waiting for server start and stopping server
  test/server/GraknRunner.java
Labels: type: bug

#93 Fix Grakn Cluster runner using invalid ports
  test/server/GraknClusterRunner.java
Labels: priority: high, type: bug

#94 Fixes for Grakn Core assembly test to not fail under Windows
  test/Runner.java
  test/server/GraknRunner.java
Labels: priority: high, type: bug, type: build

#95 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#97 Allow running console without script file
  test/console/ConsoleRunner.java
Labels: type: feature

#98 Fix ASCII header on Windows
  binary/grakn.bat
Labels: priority: medium, type: bug
