Repository vaticle/typedb-common, pull requests merged in 2021-01, with the labels that each got.

#74 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#76 Move the actor package to graknlabs/grakn
  concurrent/actor/Actor.java
  concurrent/actor/EventLoop.java
  concurrent/actor/EventLoopGroup.java
Labels: type: refactor

#75 Bump year in license headers to 2021
  .bazelrc
  .gitignore
  .grabl/automation.yml
  BUILD
  WORKSPACE
  binary/BUILD
  binary/grakn
  binary/grakn-bin.spec
  binary/grakn-docker.sh
  binary/grakn.bat
  collection/Bytes.java
  collection/Collections.java
  collection/Either.java
  collection/Pair.java
  collection/Triple.java
  concurrent/NamedThreadFactory.java
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/update.sh
  deployment.bzl
  exception/ErrorMessage.java
  test/server/BUILD
  test/server/GraknCoreRunner.java
  test/server/GraknRunner.java
  test/server/GraknSingleton.java
  test/server/logback.xml
  test/server/rules.bzl
  util/Objects.java
Labels: type: build

#77 Fix Grakn binary script for Windows
  binary/grakn.bat
Labels: priority: blocker, type: bug

#78 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build
