Repository vaticle/typedb-common, pull requests merged in 2022-08, with the labels that each got.

#128 Fix runner archive extraction error
  test/Util.java
Labels: priority: medium, type: bug

#129 Refactor runner, adding support for kotlin
  test/BUILD
  test/Util.java
  test/cluster/TypeDBClusterServerRunner.java
  test/console/TypeDBConsoleRunner.java
  test/core/TypeDBCoreRunner.java
  test/rules.bzl
Labels: priority: blocker, type: refactor

#131 Add collections helper methods
  collection/Collections.java
Labels: priority: high, type: feature
