Repository vaticle/typedb-common, pull requests merged in 2024-01, with the labels that each got.

#162 Fix line endings for TypeDB batch launcher
  .gitattributes
  BUILD
  binary/typedb.bat
Labels: priority: high, type: bug

#161 Remove binary package and test runners
  .factory/automation.yml
  BUILD
  binary/BUILD
  binary/typedb
  binary/typedb.bat
  binary/typedb.service
  test/BUILD
  test/TypeDBRunner.java
  test/TypeDBSingleton.java
  test/Util.java
  test/cloud/CloudServerOpts.java
  test/cloud/TypeDBCloudRunner.java
  test/cloud/TypeDBCloudServerRunner.java
  test/console/TypeDBConsoleRunner.java
  test/core/TypeDBCoreRunner.java
  test/logback.xml
  test/rules.bzl
Labels: priority: medium, type: refactor

#163 Move conf package to typedb-cloud
  BUILD
  conf/cloud/Addresses.java
Labels: priority: low, type: refactor

#164 Migrate artifact hosting to cloudsmith
  .factory/automation.yml
  BUILD
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: type: build

#165 Sync dependencies in CI
  .factory/automation.yml
Labels: priority: high, type: build

#166 Explicitly install python tool dependencies
  BUILD
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: priority: high, type: build

#167 Deploy artifacts in development
  .factory/automation.yml
Labels: priority: blocker, type: build

#168 Remove SonarCloud analysis job
  .factory/automation.yml
Labels: priority: medium, type: build
